# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd4fe22bbd15fa8d7e0b73cafce739f561fde2f5ab072ac4cfdc06637af73d14e99b25971c508e11cf245926f1e30f2c76d3e0238a7d37b76107be78f306f495

test:
  secret_key_base: 4bf67e0b7bc9d67c20ae0fec15f13f6680fb583a9f9d22224a401f50ec0d6de46077b790201fd9971f4d55abeee6ea0b8cb44f9ad68a281bec8d229b45ab7dd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
